name: 'Diff'
description: 'A GitHub Action that detects changes between commits/branches'
author: 'Achieve 3000. <developers@achieve3000.com>'
inputs:
  modules:
    required: true
    default: '---'
    description: 'YAML containing modules to track'
runs:
  using: 'node12'
  main: 'dist/index.js'
