name: Migrate Repository

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: [ubuntu-latest]
    steps:
      - name: Migrate Repo
        uses: achieve-3000/ghe-migration-scripts/migrate-repo/action.yml@v1.0.0
        with:
          source_repo: ${{ github.repository }}
          target_repo: "mcgrawhill-llc/a3k-diff-action"
          source_url: ${{ github.server_url }}
          source_token: ${{ secrets.CI_PAT }}
          target_token: ${{ secrets.GH_MIGRATION_TOKEN }}
      - name: Migrate Secrets
        uses: achieve-3000/ghe-migration-scripts/migrate-secrets/action.yml@v1.0.0
        with:
            source_repo: ${{ github.repository }}
            target_repo: "mcgrawhill-llc/a3k-diff-action"
            source_url: ${{ github.server_url}}
            source_token: ${{ secrets.CI_PAT }}
            target_token: ${{ secrets.GH_MIGRATION_TOKEN }}