name: Migrate Repository and secrets

on:
  workflow_dispatch:

jobs:
  migrate:
    steps:
      - name: Migrate Repo
        uses: achieve-3000/ghe-migration-scripts/migrate-repo@v1
        with:
          source_repo: ${{ github.repository }}
          target_repo: "mcgrawhill-llc/a3k-diff-action"
          source_url: ${{ github.server_url }}
          source_token: ${{ secrets.CI_PAT }}
          target_token: ${{ secrets.GH_MIGRATION_TOKEN }}
  migrate-secrets:
    steps:
      - name: Migrate Secrets
        uses: achieve-3000/ghe-migration-scripts/migrate-secrets@v1
        with:
          source_repo: ${{ github.repository }}
          target_repo: "mcgrawhill-llc/a3k-diff-action"
          source_url: ${{ github.server_url}}
          source_token: ${{ secrets.CI_PAT }}
          target_token: ${{ secrets.GH_MIGRATION_TOKEN }}
